import Head from 'next/head';
import Breadcums from '../components/common/Breadcums';
import Layout from '../components/common/Layout';
import Details from '../components/Home/Details';
import MyLead from '../components/Home/MyLead';
import Overview from '../components/Home/Overview';
import Recommendations from '../components/Home/Recommendations';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Solve Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
          <Breadcums />
          <Overview />
          <Recommendations />
          <Details />
          <MyLead />
      </Layout>
      
    </div>
  )
}
